name: Tests
on:
  push:
    branches:
     - '**'
  pull_request:

jobs:
  test:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - "1.10"
          - "2.10"
          - "2.11"
        cartridge:
          - "2.8.6"
          - "2.9.0"
          - "2.10.0"
          - "2.11.0"
          - "2.12.4"
          - "2.13.0"
          - "2.16.4"
        metrics:
          - "1.0.0"
          - "1.1.0"
          - "1.2.0"
          - "1.6.1"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: tarantool/setup-tarantool@v3
        if: matrix.tarantool != '2.x-latest'
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/2/installer.sh | sudo bash
          sudo apt install -y tt
          tt version

      # Stop Mono server. This server starts and listens to 8084 port that is
      # used for tests.
      - name: 'Stop Mono server'
        run: sudo kill -9 $(sudo lsof -t -i tcp:8084) || true

      - name: lint
        run: make lint
        env:
          CARTRIDGE_VERSION: ${{ matrix.cartridge }}
          METRICS_VERSION: ${{ matrix.metrics }}

      - name: test
        run: make test_with_coverage_report

